# Puerto del API Gateway
GATEWAY_PORT=8080

# Rutas: prefijo en el gateway → URL base del microservicio
route.usuarios.path=/api/usuarios
route.usuarios.target=http://localhost:8081

route.libros.path=/api/libros
route.libros.target=http://localhost:8082

route.autores.path=/api/autores
route.autores.target=http://localhost:8082

route.categorias.path=/api/categorias
route.categorias.target=http://localhost:8082

route.editoriales.path=/api/editoriales
route.editoriales.target=http://localhost:8082

route.prestamos.path=/api/prestamos
route.prestamos.target=http://localhost:8083

# Agregar al final del archivo existente
route.notificaciones.path=/api/notificaciones
route.notificaciones.target=http://localhost:8084

route.listaespera.path=/api/lista-espera
route.listaespera.target=http://localhost:8082
