# Puerto del API Gateway
GATEWAY_PORT=8080

# Rutas: prefijo en el gateway → URL base del microservicio
route.usuarios.path=/api/usuarios
route.usuarios.target=http://localhost:8081

route.libros.path=/api/libros
route.libros.target=http://localhost:8082

