# ── Base de datos ────────────────────────────────────────────────────────────
DB_URL=jdbc:postgresql://localhost:5432/ms_notificaciones
DB_USER=postgres
DB_PASS=6784

# ── Servidor HTTP ─────────────────────────────────────────────────────────────
SERVER_PORT=8084

# URL del microservicio de notificaciones (para referencia interna)
MS_NOTIFICACIONES_URL=http://localhost:8084
