SERVER_PORT=8083
DB_URL=jdbc:postgresql://localhost:5432/ms_prestamos_db
DB_USER=postgres
DB_PASS=6784

# URLs internas de los otros microservicios para validación
MS_USUARIO_URL=http://localhost:8081
MS_LIBROS_URL=http://localhost:8082

#URL del microservicio de notificaciones
MS_NOTIFICACIONES_URL=http://localhost:8084

DEV_MODE=true
DEV_DIAS_ENTREGA=3
